//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Businesses = new HashSet<Business>();
            this.Properties = new HashSet<Property>();
        }
    
        public byte ID { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string profile_photo { get; set; }
        public System.DateTime added_on { get; set; }
        public byte added_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<byte> modified_by { get; set; }
    
        public virtual User AddedBy { get; set; }
        public virtual User ModifiedBy { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
