//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public string type { get; set; }
        public Nullable<int> property_id { get; set; }
        public Nullable<int> business_id { get; set; }
        public string file_location { get; set; }
        public System.DateTime added_on { get; set; }
        public byte added_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<byte> modified_by { get; set; }
        public int ID { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Property Property { get; set; }
        public virtual User AddedBy { get; set; }
        public virtual User ModifiedBy { get; set; }
    }
}
