//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Businesses = new HashSet<Business>();
            this.Properties = new HashSet<Property>();
        }
    
        public short ID { get; set; }
        public string country_code { get; set; }
        public string telephone_code { get; set; }
        public string common_name { get; set; }
        public string formal_name { get; set; }
        public byte lang { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual Language Language { get; set; }
    }
}
