//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Pages = new HashSet<Page>();
            this.Businesses = new HashSet<Business>();
            this.Categories = new HashSet<Category>();
            this.Countries = new HashSet<Country>();
            this.Properties = new HashSet<Property>();
            this.PropertyTypes = new HashSet<PropertyType>();
            this.States = new HashSet<State>();
            this.Suburbs = new HashSet<Suburb>();
        }
    
        public byte ID { get; set; }
        public string LanguageName { get; set; }
        public string DisplayName { get; set; }
        public string ISO639x { get; set; }
    
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<PropertyType> PropertyTypes { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<Suburb> Suburbs { get; set; }
    }
}
