//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Businesses = new HashSet<Business>();
            this.Properties = new HashSet<Property>();
            this.Suburbs = new HashSet<Suburb>();
        }
    
        public byte ID { get; set; }
        public string state_name { get; set; }
        public byte lang { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Suburb> Suburbs { get; set; }
    }
}
