//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        public Suburb()
        {
            this.Businesses = new HashSet<Business>();
            this.Properties = new HashSet<Property>();
        }
    
        public short ID { get; set; }
        public string name { get; set; }
        public byte lang { get; set; }
        public byte state_id { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual Language Language { get; set; }
        public virtual State State { get; set; }
    }
}
