//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public byte ID { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string display_name { get; set; }
        public string email { get; set; }
        public System.DateTime registered_on { get; set; }
    }
}
